# Generated by Django 5.2.17 on 2026-08-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('wing_type', models.CharField(choices=[('LANGUAGE', 'Language Wing'), ('OPERATIONAL', 'Operational Team')], default='LANGUAGE', max_length=20)),
                ('language_code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_wings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_wing', models.CharField(choices=[('MEMBER', 'Member'), ('COORDINATOR', 'Coordinator')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wing_memberships', to=settings.AUTH_USER_MODEL)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='wings.wing')),
            ],
            options={
                'ordering': ['wing', 'user__username'],
                'unique_together': {('wing', 'user')},
            },
        ),
    ]
